# -*- coding: utf-8 -*-
"""Àlgebra(sympy).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gVEREWszZMlyw340KMpPvjE-S0Hp1Wz_

**Llibreries**
 * SymPy
   * Biblioteca de python per matemàtiques simbòliques.
   * Documentació: https://docs.sympy.org/latest/index.html
   
**Tasca:**
 * Carrega la llibreria 'sympy' amb el nom 'sym'.
"""



"""**Indicacions:**
  * Per establir una incògnita de treball fem servir ' z = sym.Symbol('z')' .

**Tasca:**
* Estableix com 'x' la incògnita amb la qual treballarem als polinomis.
"""



"""**Tasca:**
  * Realitza la **suma** dels següents polinomis: 
    * $P(x)=6x^3 + 7x^2 + 8x - 3$
    * $Q(x)=-4x^2 + 2x + 1$
    * El resultat del procès hauria de ser: $6x^3 + 3x^2 + 10x - 2$
"""



"""**Tasca:** 
  * Realitza la **resta** dels següents polinomis: 
    * $P(x)=8x^3 + 5x^2 + 4x - 3$
    * $Q(x)=-8x^3 + 9x^2 - 2x + 9$
    * El resultat del procès hauria de ser: $16x^3 - 4x^2 + 6x - 12$
"""



"""**Indicacions:** 
 * Per desenvolupar un polinomi en termes cal fer servir la instrucció 'sym.expand(Polinomi)'.

**Tasca:** 
  * Realitza la **multiplicació** dels següents polinomis: 
    * $P(x)=-6x^3 - 3x^2 - 6x + 4$
    * $Q(x)=-6x^3 + 2x^2 + 7x + 9$
    * El resultat del procès hauria de ser: $36x^6 + 6x^5 - 12x^4 - 111x^3 - 61x^2 - 26x + 36$
"""



"""**Indicacions:** 
 * Podem calcular la **divisió entera de dos polinomis** amb la instrucció 'Polinomi_Quocient, Polinomi_Residu = sym.div(Polinomi_Divident, Polinomi_Divisor)'.

**Tasca:** 
  * Realitza la **divisió** dels següents polinomis: 
    * $P(x)=12x^5 - 42x^4 + 2x^3 - 12x^2 - 57x - 11$
    * $Q(x)=2x^2 - 7x - 1$
    * El resultat del procès hauria de ser: 
      * Quocient= $6x^3 + 4x + 8$
      * Residu= $3x - 3$
"""



"""**Tasca:** 
  * Realitza el **quadrat** del següent polinomi: 
    * $P(x)=-6x^3 - 4x^2 - 7x + 4$
    * El resultat del procès hauria de ser: $36x^6 + 48x^5 + 100x^4 + 8x^3 + 17x^2 - 56x + 16$
"""



"""**Indicacions:** 
 * Podem calcular el **màxim comú divisor** de dos polinomis amb la instrucció 'sym.gcd(Polinomi_A, Polinomi_B)'.

**Tasca:** 
  * Realitza el **MCD** dels següents polinomis: 
    * $P(x)=-8x^5 + 5x^4 - 27x^3 + 28x^2 + 15x - 5$
    * $Q(x)=-48x^5 + 54x^4 - 49x^3 + 33x^2 + 35x - 5$
    * El resultat del procès hauria de ser: $8x^2 - 5x - 5$
"""



"""**Indicacions:** 
 * Podem calcular el **mínim comú múltiple** de dos polinomis amb la instrucció 'sym.lcm(Polinomi_A, Polinomi_B)'.

**Tasca:** 
  * Realitza el **mcm** dels següents polinomis: 
    * $P(x)=20x^3 + 196x^2 + 549x + 324$
    * $Q(x)=-50x^3 - 305x^2 - 392x - 144$
    * El resultat del procès hauria de ser: $-100x^4 - 1060x^3 - 3529x^2 - 3816x - 1296$
"""



"""**Indicacions:** 
 * Podem calcular la **factorització** d'un polinomi amb la instrucció 'sym.factor(Polinomi)'.

**Tasca:** 
  * Realitza el **quadrat** del següent polinomi: 
    * $P(x)=-224x^3 - 356x^2 + 203x + 245$
    * El resultat del procès hauria de ser: $( + 7)(7x + 5)(8x - 7)$
"""



"""**Indicacions:** 
 * Podem calcular la **divisió entera de dos polinomis** amb la instrucció 'Polinomi_Quocient, Polinomi_Residu = sym.div(Polinomi_Divident, Polinomi_Divisor)'.

**Tasca:** 
  * Simplifica la següent fracció algebraica: 
    * $\frac{5x^4 - 36x^3 + 26x^2 + 69x - 54}{-8x^3 + 45x^2 + 17x + 6}$ 
    * El resultat del procès hauria de ser:

**Indicacions:** 
 * Podem calcular les **arrels d'un polinomi** amb la instrucció 'sym.solve(Polinomi, Incognita)'.

**Tasca:** 
  * Deternima les **arrels** del següent polinomi: 
    * $P(x)=245x^3 - 147x^2 - 80x + 48$
    * El resultat del procès hauria de ser: [-4/7, 4/7, 3/5]
"""



"""**Indicacions:** 
 * Podem calcular la **derivada** d'una funció amb la instrucció 'sym.diff(Funció, Incognita)'.

**Tasca:** 
  * Realitza la **derivada** del següent polinomi: 
    * $P(x)=-8x^3 + 7x^2 + 3x - 10$
    * El resultat del procès hauria de ser: $-24x^2 + 14x + 3$
"""



"""**Indicacions:** 
 * Podem calcular la **Integral indefinida** d'una funció amb la instrucció 'sym.integrate(Funció, Incognita)'.

**Tasca:** 
  * Realitza la **Integral indefinida** del següent polinomi: 
    * $P(x)=-4x^3 - 6x^2 + 5x - 8$
    * El resultat del procès hauria de ser: $-x^4 - 2x^3 + 5/2x^2 - 8x$
"""



print("Divisió:", sym.factor(P/Q))  # Resultat factoritzat.